### ISSUE TITLE
Stream reset when getting snapshot

### ISSUE THREAD

**Issue by sandro628** [Petersoj/alpaca-java#106]
I'm trying to run `MarketDataEndpoint#getSnapshots(Collection<String> symbols)` with about 7000 symbols and it causes the following exception to be thrown:

```
Exception in thread "main" net.jacobpeterson.alpaca.rest.AlpacaClientException: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
	at net.jacobpeterson.alpaca.rest.AlpacaClient.request(AlpacaClient.java:208)
	at net.jacobpeterson.alpaca.rest.AlpacaClient.requestJSON(AlpacaClient.java:159)
	at net.jacobpeterson.alpaca.rest.AlpacaClient.requestObject(AlpacaClient.java:137)
	at net.jacobpeterson.alpaca.rest.AlpacaClient.requestObject(AlpacaClient.java:119)
	at net.jacobpeterson.alpaca.rest.endpoint.MarketDataEndpoint.getSnapshots(MarketDataEndpoint.java:250)
	at dev.aello.algotest.AlgoTest.createRegressions(AlgoTest.kt:71)
	at dev.aello.algotest.AlgoTest.main(AlgoTest.kt:41)
	at dev.aello.algotest.AlgoTestKt.main(AlgoTest.kt:12)
	at dev.aello.algotest.AlgoTestKt.main(AlgoTest.kt)
Caused by: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:148)
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at net.jacobpeterson.alpaca.rest.AlpacaClient.executeRequest(AlpacaClient.java:222)
	at net.jacobpeterson.alpaca.rest.AlpacaClient.request(AlpacaClient.java:202)
	... 8 more
```

I don't think there should be a limit on the number of tickers, so I'm not sure what would cause such a thing to happen.

(And to add on I did quite a bit of digging into source and it doesn't seem to be a timeout. but something related to headers?)

**Comment by Petersoj** [comment]
I can confirm this, but I don't think this is an issue with the way the internal `OkHttpClient` instance is configured. It appears to be an issue with the request URI length being too long.
Executing the following:
`curl -H "APCA-API-KEY-ID: <key ID>" -H "APCA-API-SECRET-KEY: <Secret>" -v https://data.alpaca.markets/v2/stocks/snapshots?symbols=<CSV list of 5000+ symbols>` with HTTP/2 yields the following error response from curl:
```
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* TLSv1.2 (IN), TLS alert, close notify (256):
* Empty reply from server
* Connection #0 to host data.alpaca.markets left intact
curl: (52) Empty reply from server
* Closing connection 0
```
which I believe is causing that `StreamResetException: stream was reset: CANCEL` exception. 
The interesting thing is that when executing the following:
`curl -H "APCA-API-KEY-ID: <key ID>" -H "APCA-API-SECRET-KEY: <Secret>" -v --http1.1 https://data.alpaca.markets/v2/stocks/snapshots?symbols=<CSV list of 5000+ symbols>` with HTTP/1.1, the following response from curl is this:
```
<html>
<head><title>414 Request-URI Too Large</title></head>
<body>
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
```
So even if the `OkHttpClient` instance that `alpaca-java` uses internally is set to only use HTTP/1.1 and not HTTP/2, this issue would still persist. Looks like the only resolution here is to split up your snapshot queries into multiple pieces. I've found that 2000 symbols works fine, but 4000 does not. So there's a sweet spot in between there. If Alpaca's HTTP servers increased the client header buffer size (as seen [here](https://stackoverflow.com/a/1067462/4352701)), then you could probably get away with a 7000 symbol snapshot.
