### ISSUE TITLE
Need help understanding how to overcome a suspected SSL issue

### ISSUE THREAD

**Issue by pphdevel** [Petersoj/alpaca-java#129]
After creating an AlpacaAPI object I run the account method which calls getAccountInfo(), that is how far I get. All the account details and API keys are correct but there seems to be an issue within the interaction within OKHttpClient. obviously I want to use your implementations rather that more native OKHttp, have you experienced this issue before and if so how do I look to overcome it. I have done extensive research online but don't seem to be able to sort this issue, the main feedback has been trusting the unsigned ssl certs. I am using a Spring Boot implementation which starts a Tomcat Server. then calls the API. The stack I get is:

```
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make field private final sun.security.ssl.SSLContextImpl sun.security.ssl.SSLSocketFactoryImpl.context accessible: module java.base does not "opens sun.security.ssl" to unnamed module @954b04f
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at okhttp3.internal.Platform.readFieldOrNull(Platform.java:417)
	at okhttp3.internal.Platform.trustManager(Platform.java:91)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:184)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:60)
	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:718)
	at net.jacobpeterson.alpaca.AlpacaAPI.<init>(AlpacaAPI.java:143)
	at net.jacobpeterson.alpaca.AlpacaAPI.<init>(AlpacaAPI.java:102)
```

**Comment by Petersoj** [comment]
This looks like a Java 14+ module issue. You need to add the necessary required/open declarations to your project's `module-info.java` or if you're not using a 'moduled' project, add `--add-opens java.base/sun.security.ssl=ALL-UNNAMED` to your build's JVM arguments.

**Comment by Petersoj** [comment]
@pphdevel were you able to resolve you issue?

**Comment by pphdevel** [comment]
Afternoon Jacob,

Apologies for the delay, i was away over the holidays. To be honest i tried
the fixes you suggested and i didn't have any luck but i didn't spend a
whole lot of time on it. I will be having another look at it this week as i
want to try again to interact with Alpaca.

If you have any other ideas then i would be grateful. I will keep you
posted if i make progress.

Thank you for you help as always. I am using the instance in a spring
application which runs on a tomcat server, this may be causing additional
issues. Not sure if i mentioned that, i think i did.

Kindest regards

Phil.

**Comment by Petersoj** [comment]
@pphdevel sorry for the delayed response. Were you able to figure it out?

**Comment by Petersoj** [comment]
Stale issue so closing. Re-open as needed.
