### ISSUE TITLE
Requesting a New Market Order is always Throwing the 422 Unprocessable Entity Status Code

### ISSUE THREAD

**Issue by tamuseanmiller** [Petersoj/alpaca-java#77]
I'm a few commits behind, but I don't think anything was changed on this front and was hoping for some help. Here's the logcat from the event though I don't think it is particularly useful:

`2020-10-26 10:48:05.771 3147-3147/com.bedefined.alpaca_dashboard W/System.err: net.jacobpeterson.alpaca.rest.exception.AlpacaAPIRequestException: Alpaca API Request Exception! : Status Code = 422, Status Text = "Unprocessable Entity", API Response Code = 40010001, API Response Message = "only type="limit" is allowed for extended hours orders"
2020-10-26 10:48:05.771 3147-3147/com.bedefined.alpaca_dashboard W/System.err:     at net.jacobpeterson.alpaca.AlpacaAPI.requestNewOrder(AlpacaAPI.java:481)
2020-10-26 10:48:05.771 3147-3147/com.bedefined.alpaca_dashboard W/System.err:     at net.jacobpeterson.alpaca.AlpacaAPI.requestNewMarketOrder(AlpacaAPI.java:507)
2020-10-26 10:48:05.771 3147-3147/com.bedefined.alpaca_dashboard W/System.err:     at com.bedefined.alpaca_dashboard.PlaceOrderFragment.lambda$null$4$PlaceOrderFragment(PlaceOrderFragment.java:51)
2020-10-26 10:48:05.771 3147-3147/com.bedefined.alpaca_dashboard W/System.err:     at com.bedefined.alpaca_dashboard.-$$Lambda$PlaceOrderFragment$Usfum6cYPNAIO_-730mJUFgVpDU.onClick(Unknown Source:10)
2020-10-26 10:48:05.771 3147-3147/com.bedefined.alpaca_dashboard W/System.err:     at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
2020-10-26 10:48:05.771 3147-3147/com.bedefined.alpaca_dashboard W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2020-10-26 10:48:05.771 3147-3147/com.bedefined.alpaca_dashboard W/System.err:     at android.os.Looper.loop(Looper.java:223)
2020-10-26 10:48:05.771 3147-3147/com.bedefined.alpaca_dashboard W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7656)
2020-10-26 10:48:05.771 3147-3147/com.bedefined.alpaca_dashboard W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-10-26 10:48:05.771 3147-3147/com.bedefined.alpaca_dashboard W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2020-10-26 10:48:05.771 3147-3147/com.bedefined.alpaca_dashboard W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

This is an example command that I have tried to run:
`alpacaAPI.requestNewMarketOrder("AMD", 1, OrderSide.BUY, OrderTimeInForce.DAY, true)`

It's just throwing the AlpacaAPIRequestException and tossing a null value
![image](https://user-images.githubusercontent.com/42820988/97195411-4cafbf80-1779-11eb-9b9d-2f32d5d209e4.png)

Anything else I can add in to help let me know, this is a weird one.

**Comment by Petersoj** [comment]
In the exception stacktrace you gave, it reads `API Response Code = 40010001, API Response Message = "only type="limit" is allowed for extended hours orders"` Set the last parameter to false and you should no longer receive an exception. It's a common standard to have LIMIT orders required for extended hours trading across several US brokers.
Edit: I'll just remove the ability to set that last parameter, as market orders can never be placed during extended hours.

**Comment by tamuseanmiller** [comment]
Wow, I must be blind, apologies! Would you mind giving me an example of how to place a regular market order during market hours by chance?

**Comment by Petersoj** [comment]
Haha yeah no worries. A market order can simply be placed with the following method:
```
Order marketOrder = alpacaAPI.requestNewMarketOrder("AAPL", 100, OrderSide.BUY, OrderTimeInForce.DAY, null);
```
Refer to the example code snippet in the README [here](https://github.com/Petersoj/alpaca-java#alpacaapi-example) and the Javadoc of the AlpacaAPI class [here](https://javadoc.io/doc/net.jacobpeterson/alpaca-java/latest/net/jacobpeterson/alpaca/AlpacaAPI.html) for more information.

Edit: note that the last parameter where the null value is will be removed in the next version which I'll release later today.

**Comment by tamuseanmiller** [comment]
Really appreciate it @Petersoj this wrapper has been a life saver <3
