### ISSUE TITLE
Could not parse message: {"stream":"T.CNHI","data":{"ev":"T","T":"CNHI","i":"52983525296441","x":3,"p":10.79,"s":300,"t":1605711806562000000,"c":[14,41],"z":1}}: NumberFormatException: For input string: "52983525296441"

### ISSUE THREAD

**Issue by codeaches** [Petersoj/alpaca-java#79]
I am getting the below error since today morning. May be its just me or any one else facing the issue?

Nov 18 2020 08:03:27 AM MST - Could not parse message: {"stream":"T.CNHI","data":{"ev":"T","T":"CNHI","i":"52983525296441","x":3,"p":10.79,"s":300,"t":1605711806562000000,"c":[14,41],"z":1}}
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "52983525296441"
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:228)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.Gson.fromJson(Gson.java:975)
	at net.jacobpeterson.alpaca.websocket.marketdata.client.MarketDataWebsocketClient.handleWebsocketMessage(MarketDataWebsocketClient.java:246)
	at net.jacobpeterson.abstracts.websocket.client.AbstractWebsocketClientEndpoint.lambda$onMessage$1(AbstractWebsocketClientEndpoint.java:148)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

**Comment by Petersoj** [comment]
Looks like the Trade ID field for that JSON trade message is larger than the max value of a signed integer. This is simply fixed by changing that field type to a long instead of an int in the JSON schema. Thanks for reporting this! I’ll push a new release soon.

**Comment by Petersoj** [comment]
Fixed in version `6.0.1`.
